[workspace]
members = ["bangumi", "forrit*"]

[package]
name    = "forrit"
version = "0.1.0"
edition = "2021"

[dependencies]
forrit-core = { version = "0.1.0", path = "forrit-core" }

tokio          = { version = "1.21.2", default-features = false, features = ["rt", "macros"] }
rustify_derive = { version = "0.5.2", path = "../rustify/rustify_derive" }
rustify        = { version = "0.5.3", path = "../rustify" }

color-eyre = "0.6.2"
clap       = "4.0.18"
tap        = "1.0.1"
serde      = "1.0.147"

[profile.release]
# strip         = true
lto           = true
opt-level     = "z"
codegen-units = 1
panic         = "abort"
