[resolver]
tmdb_api_key = "AAAAABBBBBCCCCCDDDDDEEEEEFFFFF"
tmdb_rate_limit = 40

[resolver.index]
enable = true
start_at_begin = true
interval = "7d"       # Re-index every 7 days

[database]
url = "mongodb://localhost:27017"
database = "forrit"

[sourcer.acg_rip]
type = "rss"
url = "https://acg.rip/.xml"
update_interval = "1m"
deny_non_torrent = false

[downloader]
type = "qbittorrent"          # Supported: "qbittorrent", "transmission"
url = "http://localhost:8080" # Default to "http://localhost:9091/transmission/rpc" for Transmission

[downloader.rename]
enable = true
interval = "5m"
format = "full" # Supported: "full", "short"

[http]
enable = true
log = true
debug = false         # Default to true for release build and false for debug build
bind = "0.0.0.0:8080"
api_path = "/api"

[http.api_doc]
enable = true
path = "/doc"
