use forrit_core::model::{Download, ListParam, ListResult, WithId};
use mongodb::bson::doc;
use salvo::{oapi::endpoint, prelude::*};
use tap::Pipe;

use crate::{
    api::{ApiResult, OidParam},
    db::Storage,
    downloader::DownloadIdx,
};

/// List all downloads generated by a subscription
#[endpoint]
async fn list_downloads(pod: &Depot, id: OidParam, param: ListParam) -> ApiResult<Json<ListResult<WithId<Download>>>> {
    pod.obtain::<Storage<Download>>()
        .expect("missing GetSet<Download>")
        .list_by(doc! { DownloadIdx::SUBSCRIPTION_ID : id.id }, param)
        .await?
        .pipe(Json)
        .pipe(Ok)
}

pub fn subscription_api() -> Router {
    Router::new().push(Router::with_path("subscription").push(Router::with_path("<id>/download").get(list_downloads)))
}
