[package]
name = "forrit-webui"

authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
forrit-config = { workspace = true }
tracing       = { workspace = true }
serde         = { workspace = true }
tap           = { workspace = true }
tokio         = { workspace = true, features = ["fs", "process"] }

include_dir = "0.7.4"
temp-dir    = "0.1.14"
