[package]
name    = "forrit-core"
version = { workspace = true }
edition = { workspace = true }
authors = { workspace = true }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
mongodb_pagination = ["mongodb-cursor-pagination"]

[dependencies]
serde                     = { workspace = true }
futures                   = { workspace = true }
bangumi-data              = { workspace = true, features = ["ts"] }
tmdb-api                  = { workspace = true, features = ["ts"] }
iso8601                   = { workspace = true }
camino                    = { workspace = true }
url                       = { workspace = true }
chrono                    = { workspace = true }
ts-rs                     = { workspace = true, features = ["url-impl", "chrono-impl"] }
salvo-oapi                = { workspace = true, features = ["url"] }
salvo_core                = { workspace = true }
serde_json                = { workspace = true }
bson                      = { workspace = true, features = ["chrono-0_4"] }
mongodb-cursor-pagination = { workspace = true, optional = true }
pin-project-lite          = "0.2.14"
