[package]
name    = "forrit-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde        = { workspace = true }
futures      = { workspace = true }
bangumi-data = { workspace = true, features = ["ts"] }
tmdb-api     = { workspace = true, features = ["ts"] }
iso8601      = { workspace = true }
camino       = { workspace = true }
url          = { workspace = true }
chrono       = { workspace = true }
regex        = { workspace = true }
tracing      = { workspace = true }
ts-rs        = { workspace = true, features = ["url-impl", "chrono-impl"] }
salvo-oapi   = { workspace = true, features = ["url"] }
bson         = { workspace = true, features = ["chrono-0_4"] }
