[package]
name    = "forrit-server"
version = "0.1.0"
edition = "2021"

[dependencies]
forrit-core = { version = "0.1.0", path = "../core" }

serde        = { workspace = true }
futures      = { workspace = true }
bson         = { workspace = true }
bangumi-data = { workspace = true }
tmdb-api     = { workspace = true }
iso8601      = { workspace = true }
camino       = { workspace = true }
url          = { workspace = true }
chrono       = { workspace = true }
reqwest      = { workspace = true }
regex        = { workspace = true }
tracing      = { workspace = true }
tokio        = { workspace = true, features = ["macros", "rt-multi-thread"] }


figment            = { version = "0.10.15", features = ["env", "json", "toml", "yaml"] }
governor           = { version = "0.6.0", default-features = false, features = ["futures", "std", "quanta"] }
mongodb            = { version = "2.8.0", features = ["bson-chrono-0_4"] }
ractor             = { version = "0.9.6", default-features = false, features = ["tokio_runtime"] }
salvo              = { version = "0.66.2", features = ["oapi", "websocket"] }
tracing-subscriber = { version = "0.3.18", features = ["json", "env-filter"] }

anitomy         = "0.2.0"
dirs            = "5.0.1"
humantime-serde = "1.1.1"
mod_use         = "0.2.1"
qbit-rs         = "0.4.1"
rss             = "2.0.6"
tap             = "1.0.1"
either          = "1.10.0"
thiserror       = "1.0.58"
humantime       = "2.1.0"
serde_json      = "1.0.114"

[dev-dependencies]
tracing-appender = "0.2.3"
tracing-flame    = "0.2.0"
dotenvy          = "0.15.7"

figment = { version = "0.10.15", features = ["env", "json", "toml", "yaml", "test"] }
tokio   = { workspace = true, features = ["full"] }
