[package]
name    = "forrit-server"
version = "0.1.0"
edition = "2021"

[dependencies]
forrit-core = { version = "0.1.0", path = "../core" }

uuid    = { workspace = true }
serde   = { workspace = true }
futures = { workspace = true }

camino             = { version = "1.1.6", features = ["serde", "serde1"] }
figment            = { version = "0.10.15", features = ["env", "json", "toml", "yaml"] }
governor           = { version = "0.6.0", default-features = false, features = ["futures", "std", "quanta"] }
iso8601            = { version = "0.6.1", features = ["chrono"] }
mongodb            = { version = "2.8.0", features = ["bson-chrono-0_4"] }
ractor             = { version = "0.9.6", default-features = false, features = ["tokio_runtime"] }
reqwest            = { version = "0.11.23", features = ["json"] }
salvo              = { version = "0.66.2", features = ["oapi"] }
tmdb-api           = { version = "0.7", git = "https://github.com/George-Miao/tmdb-api.git" }
tokio              = { version = "1.35.1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3.18", features = ["json"] }
url                = { version = "2.5.0", features = ["serde"] }

anitomy         = "0.2.0"
bangumi-data    = "0.1.2"
chrono          = "0.4.35"
dirs            = "5.0.1"
humantime-serde = "1.1.1"
mod_use         = "0.2.1"
qbit-rs         = "0.4.1"
regex           = "1.10.3"
rss             = "2.0.6"
tap             = "1.0.1"
tracing         = "0.1.40"
either          = "1.10.0"

[dev-dependencies]
tracing-appender = "0.2.3"
dotenvy          = "0.15.7"
serde_json       = "1.0.114"

figment = { version = "0.10.15", features = ["env", "json", "toml", "yaml", "test"] }
tokio   = { version = "1.35.1", features = ["full"] }
