[package]
name    = "integration"
version = "0.1.0"
edition = "2021"

[dependencies]
futures       = { workspace = true }
forrit-client = { workspace = true }

tokio = { version = "1", features = ["full"] }

dotenvy  = "0.15.7"
tempfile = "3.10.1"
