name: Build & Publish
on:
  push:
    branches:
      - main
    tags:
      - "v*"
    paths:
      - "Cargo.toml"
      - "Cargo.lock"
      - "packages/**"
      - "clients/**"
      - "frontend/**"
      - "flake.nix"
      - "flake.lock"
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Setup Nix Magic Cache
        uses: DeterminateSystems/magic-nix-cache-action@main

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.7.0

      - name: Build Frontend
        run: |
          cd frontend
          pnpm i
          pnpm run build

      - name: Detect file change
        if: github.ref_type == 'branch'
        id: files-changes
        run: |
          set +e
          git add frontend/build
          git diff --quiet --exit-code frontend/build
          changed=$?
          echo "changed=$changed" >> "$GITHUB_OUTPUT"
          [[ $changed = 0 ]] && echo "Nothing changed, early exiting" && exit 0
          echo "Changed, commit & push"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add frontend/build
          git commit -m "chore(frontend): rebuild"

      - name: Push changes
        if: "${{ steps.files-changes.outputs.changed == 1 }}"
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        run: |
          nix build ".#forrit-server-docker"
          SHA_SHORT="${GITHUB_SHA::7}"
          VERSION_TAG=$(git tag --points-at "$GITHUB_SHA" --list "v*" --sort=-version:refname | head -n 1)
          IMAGE="${{ env.REGISTRY }}/george-miao/forrit"
          nix-shell -p skopeo --command "skopeo --insecure-policy copy docker-archive:$(readlink -f ./result) docker://$IMAGE:$SHA_SHORT --dest-compress-format zstd"
          nix-shell -p skopeo --command "skopeo --insecure-policy copy docker-archive:$(readlink -f ./result) docker://$IMAGE:latest --dest-compress-format zstd"
          if [[ -n "$VERSION_TAG" ]]; then
            nix-shell -p skopeo --command "skopeo --insecure-policy copy docker-archive:$(readlink -f ./result) docker://$IMAGE:$VERSION_TAG --dest-compress-format zstd"
          fi
